server.port=0
spring.kafka.producer.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.acks=all

spring.kafka.producer.properties.delivery.timeout.ms=120000
spring.kafka.producer.properties.linger.ms=0
spring.kafka.producer.properties.request.timeout.ms=30000

spring.kafka.producer.properties.max.in.flight.requests.per.connection=5
spring.kafka.producer.properties.enable.idempotence=true

withdraw-money-topic=withdraw-money-topic
deposit-money-topic=deposit-money-topic

spring.kafka.producer.transaction-id-prefix=transfer-service-${random.value}-

# Having al the logs in TRACE level, will generate more information and will become harder to track
# Enabling kafka logging
#logging.level.org.springframework.kafka.transaction=TRACE
# Enabling kafka transactions logging, this logs wont be shown since we have as well jpa transaction enable
# We need to enable kafka internal transactions logging as in line 30
logging.level.org.springframework.kafka.transaction.KafkaTransactionManager=DEBUG
# Enabling spring transactions logging
logging.level.org.springframework.transaction=DEBUG
# Enabling jpa transactions logging
logging.level.org.springframework.org.jpa.JpaTransactionManager=DEBUG
# Enabling kafka internal transactions logging
logging.level.org.apache.kafka.clients.producer.internals.TransactionManager=DEBUG

spring.datasource.username=marko
spring.datasurce.password=
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true


